<?php 
 $GLOBALS["dictionary"]["ts_Departure"]=array (
  'table' => 'ts_departure',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'inline_edit' => true,
      'duplicate_merge_dom_value' => '0',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'ts_departure_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'ts_departure_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'ts_departure_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'SecurityGroups' => 
    array (
      'name' => 'SecurityGroups',
      'type' => 'link',
      'relationship' => 'securitygroups_ts_departure',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'source' => 'non-db',
      'vname' => 'LBL_SECURITYGROUPS',
    ),
    'triple_room_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Triple Room',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'triple_room_c',
      'vname' => 'LBL_TRIPLE_ROOM',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'ts_Departuretriple_room_c',
      'custom_module' => 'ts_Departure',
    ),
    'parent_fixed_departure_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Parent Fixed Departure',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'parent_fixed_departure_c',
      'vname' => 'LBL_PARENT_FIXED_DEPARTURE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'parent_fixed_departure_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'ts_Departureparent_fixed_departure_c',
      'custom_module' => 'ts_Departure',
    ),
    'fixed_departure_cost_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fixed Departure Cost',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'fixed_departure_cost_c',
      'vname' => 'LBL_FIXED_DEPARTURE_COST',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'ts_Departurefixed_departure_cost_c',
      'custom_module' => 'ts_Departure',
    ),
    'guests_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total No. of Guests',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'guests_c',
      'vname' => 'LBL_GUESTS',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
      'id' => 'ts_Departureguests_c',
      'custom_module' => 'ts_Departure',
    ),
    'start_date_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fixed Departure Start Date',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'start_date_c',
      'vname' => 'LBL_START_DATE',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'ts_Departurestart_date_c',
      'custom_module' => 'ts_Departure',
    ),
    'ts_departure_cases_1' => 
    array (
      'name' => 'ts_departure_cases_1',
      'type' => 'link',
      'relationship' => 'ts_departure_cases_1',
      'source' => 'non-db',
      'module' => 'Cases',
      'bean_name' => 'Case',
      'side' => 'right',
      'vname' => 'LBL_TS_DEPARTURE_CASES_1_FROM_CASES_TITLE',
    ),
    'single_room_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Single Room',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'single_room_c',
      'vname' => 'LBL_SINGLE_ROOM',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'ts_Departuresingle_room_c',
      'custom_module' => 'ts_Departure',
    ),
    'rooms_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fixed Departure Capacity (Rooms)',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'rooms_c',
      'vname' => 'LBL_ROOMS',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
      'id' => 'ts_Departurerooms_c',
      'custom_module' => 'ts_Departure',
    ),
    'end_date_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fixed Departure End Date',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'end_date_c',
      'vname' => 'LBL_END_DATE',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'ts_Departureend_date_c',
      'custom_module' => 'ts_Departure',
    ),
    'fixed_departure_revenue_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fixed Departure Revenue',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'fixed_departure_revenue_c',
      'vname' => 'LBL_FIXED_DEPARTURE_REVENUE',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'ts_Departurefixed_departure_revenue_c',
      'custom_module' => 'ts_Departure',
    ),
    'parent_fixed_departure_relat_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Parent Fixed Departure',
      'required' => false,
      'source' => 'non-db',
      'name' => 'parent_fixed_departure_relat_c',
      'vname' => 'LBL_PARENT_FIXED_DEPARTURE_RELAT',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'ts_departure_id_c',
      'ext2' => 'ts_Departure',
      'module' => 'ts_Departure',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'ts_Departureparent_fixed_departure_relat_c',
      'custom_module' => 'ts_Departure',
    ),
    'quint_room_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Quint Room',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'quint_room_c',
      'vname' => 'LBL_QUINT_ROOM',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'ts_Departurequint_room_c',
      'custom_module' => 'ts_Departure',
    ),
    'location_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Location',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'location_c',
      'vname' => 'LBL_LOCATION',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'ts_Departurelocation_c',
      'custom_module' => 'ts_Departure',
    ),
    'aos_products_quotes_ts_departure_1' => 
    array (
      'name' => 'aos_products_quotes_ts_departure_1',
      'type' => 'link',
      'relationship' => 'aos_products_quotes_ts_departure_1',
      'source' => 'non-db',
      'module' => 'AOS_Products_Quotes',
      'bean_name' => 'AOS_Products_Quotes',
      'vname' => 'LBL_AOS_PRODUCTS_QUOTES_TS_DEPARTURE_1_FROM_AOS_PRODUCTS_QUOTES_TITLE',
      'id_name' => 'aos_products_quotes_ts_departure_1aos_products_quotes_ida',
    ),
    'aos_products_quotes_ts_departure_1_name' => 
    array (
      'name' => 'aos_products_quotes_ts_departure_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_AOS_PRODUCTS_QUOTES_TS_DEPARTURE_1_FROM_AOS_PRODUCTS_QUOTES_TITLE',
      'save' => true,
      'id_name' => 'aos_products_quotes_ts_departure_1aos_products_quotes_ida',
      'link' => 'aos_products_quotes_ts_departure_1',
      'table' => 'aos_products_quotes',
      'module' => 'AOS_Products_Quotes',
      'rname' => 'name',
    ),
    'aos_products_quotes_ts_departure_1aos_products_quotes_ida' => 
    array (
      'name' => 'aos_products_quotes_ts_departure_1aos_products_quotes_ida',
      'type' => 'link',
      'relationship' => 'aos_products_quotes_ts_departure_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_AOS_PRODUCTS_QUOTES_TS_DEPARTURE_1_FROM_TS_DEPARTURE_TITLE',
    ),
    'currency_id' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency_id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'dbType' => 'id',
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
      'id' => 'ts_Departurecurrency_id',
      'custom_module' => 'ts_Departure',
    ),
    'ts_departure_id_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'ts_departure_id_c',
      'vname' => 'LBL_PARENT_FIXED_DEPARTURE_RELAT_TS_DEPARTURE_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'ts_Departurets_departure_id_c',
      'custom_module' => 'ts_Departure',
    ),
    'quad_room_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Quad Room',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'quad_room_c',
      'vname' => 'LBL_QUAD_ROOM',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'ts_Departurequad_room_c',
      'custom_module' => 'ts_Departure',
    ),
    'ts_departure_leads_1' => 
    array (
      'name' => 'ts_departure_leads_1',
      'type' => 'link',
      'relationship' => 'ts_departure_leads_1',
      'source' => 'non-db',
      'module' => 'Leads',
      'bean_name' => 'Lead',
      'side' => 'right',
      'vname' => 'LBL_TS_DEPARTURE_LEADS_1_FROM_LEADS_TITLE',
    ),
    'double_room_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Double Room',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'double_room_c',
      'vname' => 'LBL_DOUBLE_ROOM',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'ts_Departuredouble_room_c',
      'custom_module' => 'ts_Departure',
    ),
    'pax_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fixed Departure Capacity (Pax)',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'pax_c',
      'vname' => 'LBL_PAX',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
      'id' => 'ts_Departurepax_c',
      'custom_module' => 'ts_Departure',
    ),
    'total_rooms_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total No. of Rooms',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_rooms_c',
      'vname' => 'LBL_TOTAL_ROOMS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'ts_Departuretotal_rooms_c',
      'custom_module' => 'ts_Departure',
    ),
    'ts_departure_ts_vendors_1' => 
    array (
      'name' => 'ts_departure_ts_vendors_1',
      'type' => 'link',
      'relationship' => 'ts_departure_ts_vendors_1',
      'source' => 'non-db',
      'module' => 'ts_Vendors',
      'bean_name' => 'ts_Vendors',
      'side' => 'right',
      'vname' => 'LBL_TS_DEPARTURE_TS_VENDORS_1_FROM_TS_VENDORS_TITLE',
    ),
    'price_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fixed Departure Price/Person',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'price_c',
      'vname' => 'LBL_PRICE',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'ts_Departureprice_c',
      'custom_module' => 'ts_Departure',
    ),
  ),
  'relationships' => 
  array (
    'ts_departure_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'ts_Departure',
      'rhs_table' => 'ts_departure',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'ts_departure_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'ts_Departure',
      'rhs_table' => 'ts_departure',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'ts_departure_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'ts_Departure',
      'rhs_table' => 'ts_departure',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'securitygroups_ts_departure' => 
    array (
      'lhs_module' => 'SecurityGroups',
      'lhs_table' => 'securitygroups',
      'lhs_key' => 'id',
      'rhs_module' => 'ts_Departure',
      'rhs_table' => 'ts_departure',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'securitygroups_records',
      'join_key_lhs' => 'securitygroup_id',
      'join_key_rhs' => 'record_id',
      'relationship_role_column' => 'module',
      'relationship_role_column_value' => 'ts_Departure',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'ts_departurepk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'security_groups' => 'security_groups',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);